version: '3'

services:
  python3:
    #restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: 'python3'
    working_dir: '/work'
    volumes:
      - '.:/work'
    tty: true
